### ISSUE TITLE
No Icon on Ubuntu

### ISSUE THREAD

**Issue by travisfont-doctena** [tmdh/laravel-kit#21] opened 2021-03-19 09:18 UTC
Empty icon shows on Ubuntu. Including, the AppImage doesn't allow to save to favorites.

**Comment by tmdh** [comment] 2021-03-26 14:41
Can you check if it's fixed in v2.0.2?

**Comment by travisfont-doctena** [comment] 2021-06-01 13:20
Still no fix.

**Comment by tmdh** [comment] 2022-01-21 11:11
Icons works in my Gnome setup in Arch Linux. Please check if the issue is still there in 2.0.5 for Ubuntu.

**Comment by tmdh** [comment] 2022-03-30 13:41
Fixed for deb release.

**Closed as completed by tmdh** 2022-03-30 13:41 UTC
Labels: bug
